### ISSUE TITLE
Feature baskets - [merged]

### ISSUE THREAD

**Issue by vishnu-kvnvv** [vishnu-kvnvv/defy-sockets#83]
In GitLab by @user-ketan on Feb 23, 2022, 13:55

_Merges feature-baskets -> main_

```
basketGraphs:
  baseInvestedAmount: 5000000
  basketGraphGranularities:
    - duration: 1M
      daysFromNow: 30
      granularity: 144
    - duration: 3M
      daysFromNow: 90
      granularity: 1
    - duration: 6M
      daysFromNow: 180
      granularity: 2
    - duration: 1y
      daysFromNow: 365
      granularity: 4
```
