### ISSUE TITLE
Resolve "basket historical data" - [merged]

### ISSUE THREAD

**Issue by vishnu-kvnvv** [vishnu-kvnvv/defy-sockets#84]
In GitLab by @user-ketan on Feb 25, 2022, 18:54

_Merges 62-basket-historical-data -> 59-baskets-socket-data_

Closes #62 
```
basketGraphs:
  baseInvestedAmount: 5000000
  basketGraphGranularities:
    - duration: 3M
      daysFromNow: 90
      granularity: 1
    - duration: 1M
      daysFromNow: 30
      granularity: 1
    - duration: 6M
      daysFromNow: 180
      granularity: 2
    - duration: 1y
      daysFromNow: 365
      granularity: 4
```
